name: Build and lint
on: pull_request

jobs:
  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - uses: actions/cache@v1.0.3
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Run install
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run lint
        run: npm run lint
